<?php

define('MQ_DEFAULT_MAX_PLAYERS', 8);
define('MQ_MAX_MAX_PLAYERS', 24);
define('MQ_DEFAULT_TOTAL_ROUNDS', 5);
define('MQ_DEFAULT_ROUND_DURATION', 30);
define('MQ_DEFAULT_REVEAL_DURATION', 10);
define('MQ_MIN_NEXT_VOTE_DELAY_SECONDS', 10);
define('MQ_MAX_CORRECT_ANSWER_SCORE', 1000);
define('MQ_MIN_CORRECT_ANSWER_SCORE', 10);
define('MQ_OWNER_STALE_TIMEOUT_SECONDS', 60);

define('MQ_MERCURE_HUB_URL', $_ENV['MQ_MERCURE_HUB_URL'] ?? $_ENV['MERCURE_HUB_URL'] ?? 'https://mercure.shinederu.ch/.well-known/mercure');
define('MQ_MERCURE_PUBLISH_URL', $_ENV['MQ_MERCURE_PUBLISH_URL'] ?? $_ENV['MERCURE_PUBLISH_URL'] ?? MQ_MERCURE_HUB_URL);
define('MQ_MERCURE_PUBLISHER_JWT_KEY', $_ENV['MQ_MERCURE_PUBLISHER_JWT_KEY'] ?? $_ENV['MERCURE_PUBLISHER_JWT_KEY'] ?? '');
define('MQ_MERCURE_SUBSCRIBER_JWT_KEY', $_ENV['MQ_MERCURE_SUBSCRIBER_JWT_KEY'] ?? $_ENV['MERCURE_SUBSCRIBER_JWT_KEY'] ?? '');
define('MQ_MERCURE_TOPIC_BASE', rtrim($_ENV['MQ_MERCURE_TOPIC_BASE'] ?? 'https://api.shinederu.ch/melodyquest/topics', '/'));
define('MQ_MERCURE_COOKIE_DOMAIN', $_ENV['MQ_MERCURE_COOKIE_DOMAIN'] ?? '.shinederu.ch');
define('MQ_MERCURE_COOKIE_PATH', $_ENV['MQ_MERCURE_COOKIE_PATH'] ?? '/.well-known/mercure');
define('MQ_MERCURE_SUBSCRIBER_TTL_SECONDS', max(30, (int)($_ENV['MQ_MERCURE_SUBSCRIBER_TTL_SECONDS'] ?? 90)));
define('MQ_MERCURE_PUBLISH_TIMEOUT_SECONDS', max(1, (int)($_ENV['MQ_MERCURE_PUBLISH_TIMEOUT_SECONDS'] ?? 3)));
